rootdir commandline parameter added + some usability fixes

diff --git a/wpbuildr b/wpbuildr
--- a/wpbuildr
+++ b/wpbuildr
@@ -10,11 +10,27 @@
 # Additionally, this script is meant to help with multi-environment deployment
 # using Aaron Holbrook's WordPress/Git deployment model (http://aaronjholbrook.com/wpvc/)
 #
-# version: 1.2 (customized by sergey)
+# version: 1.3 (customized by sergey)
 
 . ./globals.sh
-clear
-echo ""
+print_wpbuildr_usage(){
+	echo "Usage: wpbuildr <rootdir> [[project_name] [framework]]"
+	exit 1
+}
+
+if [ $# -lt 1 ];
+then
+	echo "Error: command-line argument(s) missing"
+       print_wpbuildr_usage
+fi
+
+if [ ! -d $1 ];
+then
+	echo "Error: rootdir $1 incorrect / doesn't exist!"
+	exit 2
+fi
+#clear
+#echo ""
 echo '   '
 echo '                    __          _ __    __    '
 echo '    _      ______  / /_  __  __(_) /___/ /____'
@@ -27,9 +43,11 @@ echo "wpbuildr - an Aaron Holbrook Production"
 echo "customized by sergey"
 echo ''
 
+
 OLDDIR=`pwd`
-cd ..
-DOCROOT=`pwd`
+DOCROOT=$1
+cd $DOCROOT
+
 # create the html for site-root (to mimic MT, possibly look at allowing other structures)
 # if html dir exists, exit - let's not break anything!
 if [ -f "wp-config.php" ]; then
@@ -54,10 +72,10 @@ dir="$(dirname "$(readlink "$0")")"
 # DB Name
 # theme name
 # table prefixes
-if [ ! $1 ]; then
+if [ ! $2 ]; then
   read -p "Give your project a name: " project
 else
-  project=$1
+  project=$2
 fi
 
 
@@ -79,7 +97,7 @@ fi
 # fi
 
 # Build our theme from a framework? 
-if [ ! $2 ]; then
+if [ ! $3 ]; then
   echo "What theme framework would you like to use?"
   read -p "Options: [blueox, _s, startbox, starkers, html5, bones, custom, none]: " framework
 fi
@@ -429,5 +447,6 @@ echo '------------------------------------------------------------------------'
 echo '---> WPBUILDR COMPLETE'
 echo '------------------------------------------------------------------------'
 echo ''
-
-
+echo "--- Don't forget to add remote repo and push your changes there: ---"
+echo "git remote add origin https://somehost/somepath/somerepo.git"
+echo "git push origin master"
